<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/component2.js -->
<!-- Generate a Single File Component part by running command `rails generate vue component` -->

<template>
  <div id="component2">
    <span>2nd Component:</span>
    <p>{{ shared.counter }}</p>
    <button @click="onClick">decrease</button>
  </div>
</template>

<script>
import store from '@/store'
export default {
  data: function() {
    return {
      shared: store.state,
      message: "Hello component2!"
    };
  },
  watch: {
    onCreated: function(response) {
      this.items = response.data;
    }
  },
  methods: {

    onClick: function() {
      console.log("clicked");
      this.shared.counter = this.shared.counter - 1
    }
  },
  computed: {}
};
</script>

<style scoped>

#component2 {
  border: 1px solid #d1d1d1;
  margin: 5px;
}

p {
  font-size: 2em;
  text-align: center;
}
</style>
