<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/component3.js -->
<!-- To generate a Single File Component part by running command `rails generate vue component` -->

<template>
  <div id="component3">
    <p>{{ shared.counter }}</p>
    <button @click="onClick">Reset to zero</button>
  </div>
</template>

<script>
import store from '@/store'
export default {
  data: function() {
    return {
      shared: store.state,
      message: "Hello component3!"
    };
  },
  watch: {
    onCreated: function(response) {
      this.items = response.data;
    }
  },
  methods: {
    onClick: function() {
      console.log("Component 3 invoking store.clearMessageAction()");
      // invoking the shared store's method: clearMessageAction
      store.clearMessageAction()
    }
  },
  computed: {}
};
</script>

<style scoped>

#component3 {
  border: 1px solid #d1d1d1;
  margin: 5px;
}


p {
  font-size: 2em;
  text-align: center;
}
</style>
