// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// A simple state management as described in https://vuejs.org/v2/guide/state-management.html
// At your .vue, import store from '@/store' 
// Use at your method, store.state.message or this.shared.message

var store = {
  debug: true,
  state: {
    message: "Hello from Simple Store!",
    counter: 1
  },
  setMessageAction(newValue) {
    if (this.debug) console.log("setMessageAction triggered with", newValue);
    this.state.message = newValue;
  },
  clearMessageAction() {
    if (this.debug) console.log("clearMessageAction triggered");
    this.state.counter = 0;
  }
};

export default store;
