// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./component')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue component`

import Vue from 'vue'
import App from '@/component.vue'

document.addEventListener('DOMContentLoaded', () => {
  document.body.appendChild(document.createElement('component'))
  const component = new Vue({
    render: h => h(App)
  }).$mount('component')
  console.log({component})
})
