// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./component3')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue component`

import Vue from 'vue'
import App from '@/component3.vue'

document.addEventListener('DOMContentLoaded', () => {
  document.body.appendChild(document.createElement('component3'))
  const component3 = new Vue({
    render: h => h(App)
  }).$mount('component3')
  console.log({component3})
})
