// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./component2')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue component`

import Vue from 'vue'
import App from '@/component2.vue'

document.addEventListener('DOMContentLoaded', () => {
  document.body.appendChild(document.createElement('component2'))
  const component2 = new Vue({
    render: h => h(App)
  }).$mount('component2')
  console.log({component2})
})
